import localFont from "next/font/local";
import "./globals.css";

const nulshock = localFont({
  src: [
    {
      path: "../../public/fonts/Nulshock-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Nulshock-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Nulshock-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-nulshock",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nulshock.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
